name: Openwrt Build Bot
on:
  schedule:
  - cron: 0 10 * * *

jobs:
  check:
    name: Check new version of Clash.Meta
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          ./check.sh
          current_version=$(cat Makefile | grep PKG_VERSION | head -n 1 | cut -d "=" -f 2)
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d) Bump Clash.Meta to $current_version"
          git push --force --quiet "https://x-access-token:${{ secrets.P_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:main

